### ISSUE TITLE
Dependency errors when installing on new React project

### ISSUE THREAD

**Issue by mariasereno-png** [orchestrated-io/orcs-design-system#127]
When doing a fresh ORCS install using `npm i orcs-design-system` the following errors come up:

<img width="686" alt="Screen Shot 2021-01-07 at 23 39 18" src="https://user-images.githubusercontent.com/58196822/103893947-398a7a00-5142-11eb-8d7a-409f5b068f14.png">

Environment: fresh Create React App install

It works fine if you do `npm i --force orcs-design-system` but would be good to get this sorted out sometime. :)

**Comment by mariasereno-png** [comment]
Also, looks like fortawesome needs to be in dependencies, not just dev dependencies :)

**Comment by abottega** [comment]
Thanks Maria! Will fix up

**Comment by shomukai** [comment]
@mariasereno-png , when did you created the react app?
I think it's just some of the package versions are old.

I have tried to `npx create-react-app my-app` and use yarn to install orcs-design-system, no error happened.

**Comment by mariasereno-png** [comment]
It was on January 7 @shomukai ! So it may be fixed by now :) Good to close I think!
